### ISSUE TITLE
[DSM] Mon Oct 30 2023

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/dsm#10]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by FrostByBlood** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
https://github.com/torin-asakura/planning/issues/9
- крутил иствестовские хоры, честно говоря, хоры очень устаревшие, редактор фраз неплохой, но все равно лучше залеерить с нормальной библой
https://github.com/torin-asakura/planning/issues/6
- строй в табе поправил на дроп д
#### Какие задачи будешь делать сегодня? Укажи #issues
https://github.com/torin-asakura/planning/issues/9
- буду докручивать хоры
https://github.com/torin-asakura/planning/issues/8
- начну съем
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
- с 12:00 до 13:30 буду в каче
