### ISSUE TITLE
[DSM] Thu Oct 19 2023

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/dsm#2]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by FrostByBlood** [comment]
@TorinAsakura #### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- приступил к разбору трека яд [#6](https://github.com/torin-asakura/planning/issues/6), подбирал синты и снимал гитары
#### Какие задачи будешь делать сегодня? Укажи #issues
-продолжу съем трека [#6](https://github.com/torin-asakura/planning/issues/6), попробую точнее снять тон синтов и постараюсь снять весь каркас трека целиком 
#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
- к часу в кач схожу
