### ISSUE TITLE
[DSM] Fri Sep 20 2024

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/dsm#228]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by FrostByBlood** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/torin-asakura/planning/issues/18
  - доводил до ума
- https://github.com/torin-asakura/planning/issues/19
  - мой вариант с миксом не сходится, драмка провисает
  - переделывал драмку, стандартными плагинами лоджика нужный звук крутится со скрипом
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/torin-asakura/planning/issues/19
  - продолжаю работу с драмкой 
#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)
- инет так и работает через одно место, отзвонился вчера, вызвал рабочих, в течении дня должны подойти, мобильный трафик почти весь уже потратил
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
- с 17:00 по 19:00 буду афк
- в течении дня жду рабочих, до пяти вечера должны придти
