### ISSUE TITLE
[DSM] Fri Oct 20 2023

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/dsm#3]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by FrostByBlood** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
https://github.com/torin-asakura/planning/issues/6
- разбор завершен, клавиши залиты на диск
- таба готова

#### Какие задачи будешь делать сегодня? Укажи #issues
 https://github.com/torin-asakura/planning/issues/7 
- разберу клавиши и попробую снять целиком весь каркас трека

#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
- с 18: 00 до 19: 00 прервусь на поход в магазин и ужин
