### ISSUE TITLE
[DSM] Sat Oct 21 2023

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/dsm#4]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by FrostByBlood** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
 https://github.com/torin-asakura/planning/issues/7#
- готов разбор
- подготавливается проект для переноса в табу
#### Какие задачи будешь делать сегодня? Укажи #issues
- в процессе таба https://github.com/torin-asakura/planning/issues/7#
- начну разбор https://github.com/torin-asakura/planning/issues/9
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
- с 17:00 до 18: 00 буду заниматься домашними делами
