### ISSUE TITLE
[DSM] Mon Oct 23 2023

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/dsm#5]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by FrostByBlood** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
Вчера отдыхал
#### Какие задачи будешь делать сегодня? Укажи #issues
https://github.com/torin-asakura/planning/issues/9
- продолжу разбор композиции, постараюсь целиком снять основу
