### ISSUE TITLE
[DSM] Tue Oct 24 2023

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/dsm#6]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by FrostByBlood** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
https://github.com/torin-asakura/planning/issues/9
- Подбирал основу и прорабатывал звучание
#### Какие задачи будешь делать сегодня? Укажи #issues
https://github.com/torin-asakura/planning/issues/9
- продолжу разбор трека
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
- с 14:00 до 15:30 буду в каче
