### ISSUE TITLE
[DSM] Wed Oct 25 2023

### ISSUE THREAD

**Issue by TorinAsakura** [torin-asakura/dsm#7]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by FrostByBlood** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
https://github.com/torin-asakura/planning/issues/9
- Разбирал лирическую часть и прорабатывал перкуссию
#### Какие задачи будешь делать сегодня? Укажи #issues
https://github.com/torin-asakura/planning/issues/9
- попытаюсь сегодня снять оставшиеся части
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
- с 12:00 до !3:00 надо будет пройтись по магазам
